services:
  postgres:
    image: postgres:17
    container_name: bm-erp-postgres

    environment:
      POSTGRES_DB: bm_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: